### ISSUE TITLE
win8 64 位系统无法运行

### ISSUE THREAD

**Issue by woshilaoxue888** [tiankong1999/xiaomiyoupin_maotai#4]
今天解压后，在管理员模式下运行文件，无法正常启动，win8.1 64位

**Comment by tiankong1999** [comment]
有网友反映，用的win7也打不开，换成win10就可以了。
估计是打包版本的问题，暂时还没时间看这个问题。
你先换成win10的试下，我的 win10是可以的。

另外，GitHub不稳定，我这边经常打不开，回复不及时，可以公众号后台留言。
