### ISSUE TITLE
提交不了订单，都是抢购失败，几十个号目前成功率是0

### ISSUE THREAD

**Issue by LyAmor01** [tiankong1999/xiaomiyoupin_maotai#7]

**Comment by jie15155988804** [comment]
小米有抢到过得吗

**Comment by LyAmor01** [comment]
这个脚本抢不到

**Comment by jie15155988804** [comment]
今天试了么，我朋友买的挂今天中了听他说

**Comment by LyAmor01** [comment]
6号试过，0点 10点 20点三次，50个号，全部零蛋

**Comment by LyAmor01** [comment]
你朋友买的啥挂，可以介绍下么

**Comment by jie15155988804** [comment]
我也不知道他只帮我代挂今天中了2

**Comment by LyAmor01** [comment]
能加个微信吗？15527929025

**Comment by tiankong1999** [comment]
> 6号试过，0点 10点 20点三次，50个号，全部零蛋




> 6号试过，0点 10点 20点三次，50个号，全部零蛋

同一个IP跑这么多脚本，你就不担心封号

**Comment by LyAmor01** [comment]
几个IP执行的，老板这个脚本有个bug，不能在0点抢购

**Comment by tiankong1999** [comment]
> 几个IP执行的，老板这个脚本有个bug，不能在0点抢购

23:59:59.999 不就是0点吗
先别用了，这是调试打包版本，后面有空重新上传。
